variable "env" {}
variable "tags" {}
variable "vpc" {}
variable "default_vpc_id" {}
variable "default_vpc_rt" {}
variable "rabbitmq" {}
variable "allow_ssh_cidr" {}
variable "zone_id" {}
variable "rds" {}
variable "kms_key_id" {}
variable "kms_key_arn" {}
variable "documentdb" {}
variable "elasticache" {}
variable "alb" {}
variable "apps" {}
variable "allow_prometheus_cidr" {}
variable "eks" {}
